title: CreateChibi - おちびちゃんズ化ツール
description: VRChatアバターを「おちびちゃんズ」向けに変換するUnity Editor拡張の説明書
url: "https://aramaa-vr.github.io"
baseurl: "/create-chibi"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

search_enabled: true

aux_links:
  Docs Repo: "https://github.com/aramaa-vr/create-chibi"
  Tool Repo: "https://github.com/aramaa-vr/create-chibi"
  Booth: "https://aramaa.booth.pm/items/7906711"
  Discord: "https://discord.gg/BJ3BpVnMna"

permalink: pretty
footer_content: "© Aramaa / CreateChibi"
