title: OchibiChansConverterTool - おちびちゃんズ化ツール
description: VRChatアバターを「おちびちゃんズ」向けに変換するUnity Editor拡張の説明書
url: "https://aramaa-vr.github.io"
baseurl: "/ochibi-chans-converter-tool"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

search_enabled: true

just_the_docs:
  custom_css:
    - assets/css/custom.css

aux_links:
  Docs Repo: "https://github.com/aramaa-vr/ochibi-chans-converter-tool"
  Tool Repo: "https://github.com/aramaa-vr/ochibi-chans-converter-tool"
  Booth: "https://aramaa.booth.pm/items/7906711"
  Discord: "https://discord.gg/BJ3BpVnMna"

permalink: pretty
footer_content: "© Aramaa / OchibiChansConverterTool"
